# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  before_all do
    ENV["FIREBASE_LOGIN_CREDENTIALS"] = "fastlane/firebase-login-creds.json"
    ENV["FIREBASE_APP_ID"] = "1:446356974915:android:63f8111799566ddd9d13f6"
  end


  ######## FIREBASE DISTRIBUTION  ########
  desc "Submit a new Google Test Build to Firebase App Distribution"
  lane :testGoogle do |options|
     gradle(task: "clean")
     
     gradle(task: "assemble", build_type: "release")
     puts ENV["FIREBASE_LOGIN_CREDENTIALS"]
     release_note_information = " BRANCH => #{git_branch} - developer: #{last_git_commit[:author]}"
     release_note = "#{release_note_information} \n #{options[:r]}"
     firebase_app_distribution(
           app: ENV["FIREBASE_APP_ID"],
           apk_path:"../build/app/outputs/apk/release/app-release.apk",
           release_notes: "#{release_note}",
           groups_file: "fastlane/groups.txt",
           service_credentials_file: ENV["FIREBASE_LOGIN_CREDENTIALS"],
           firebase_cli_path: "/usr/local/bin/firebase",
           debug:true,

     )
     # fastlane testGoogle r:"First Alpha Release"
  end
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
